### ISSUE TITLE
FIX: очистка  стилей таблицы.

### ISSUE THREAD

**Issue by tsukasa-mixer** [studio107/ueditor-fork#8]
При вставке таблицы из ворда подтягивается туча стилей которые автоматически нельзя очистить.

**Comment by max107** [comment]
@tsukasa-mixer можешь приложить исходник?

**Comment by tsukasa-mixer** [comment]
@max107 https://gist.github.com/tsukasa-mixer/b39c283b94a5a1cd2b057d9b087abc4d
